exports.field = ["30", "Byeong-Hun An", "Abraham Ancer", "Daniel Berger", "Christiaan Bezuidenhout", "Zac Blair", "Keegan Bradley",
"Scott Brown", "Olin Browne", "Bronson Burgoon", "Rafa Cabrera Bello", "Chad Campbell", "Bud Cauley", "Cameron Champ", "Wyndham Clark", "Keith Clearwater",
"Corey Conners", "Franklin Corpening", "Joel Dahmen", "Cameron Davis", "Jason Day", "Bryson DeChambeau", "Jason Dufner", "Tyler Duncan", "Harris English", "Tony Finau",
"Matthew Fitzpatrick", "Rickie Fowler", "Dylan Fritelli", "David Frost", "Jim Furyk", "Sergio Garcia", "Brice Garnett", "Brian Gay", "Doug Ghim", "Lucas Glover", "Talor Gooch", "Branden Grace",
"Lanto Griffin", "Emiliano Grillo", "Bill Haas", "Chesson Hadley", "Adam Hadwin", "Brian Harman", "Scott Harrington", "J.J. Henry", "Jim Herman", "Kramer Hickok",
"Harry Higgs", "Charley Hoffman", "Tom Hoge", "Max Homa", "Billy Horschel", "Beau Hossler", "Viktor Hovland", "Charles Howell III", "Mark Hubbard",
"Mackenzie Hughes", "Sungjae Im", "Jazz Janewattananond", "Zach Johnson", "Dustin Johnson", "Matt Jones", "Sung Kang", "Si Woo Kim", "Chris Kirk", "Kevin Kisner",
"Patton Kizzire", "Russell Knox", "Brooks Koepka", "Jason Kokrak", "Matt Kuchar", "Andrew Landry", "Bernhard Langer", "Nate Lashley", "Kyoung-Hoon Lee", "Danny Lee",
"Tom Lehman", "Marc Leishman", "Tom Lewis", "Adam Long", "Shane Lowry", "Scott McCarron", "Denny McCarthy", "Tyler McCumber", "Graeme McDowell", "Rory McIlroy", "Maverick McNealy", "Troy Merritt",
"Phil Mickelson", "Keith Mitchell", "Ryan Moore", "Collin Morikawa", "Sebastián Muñoz", "Kevin Na", "Matthew NeSmith", "Joaquin Niemann", "Alex Noren", "Henrik Norlander", "Andy Ogletree", "Louis Oosthuizen",
"Carlos Ortiz", "Ryan Palmer", "C.T. Pan", "Pat Perez", "Victor Perez", "Scott Piercy", "JT Poston", "Ian Poulter", "Andrew Putnam", "Jon Rahm", "Chez Reavie", "Doc Redman", "Patrick Reed",
"Patrick Rodgers", "Justin Rose", "Sam Ryder", "Rory Sabbatini", "Xander Schauffele", "Scottie Scheffler", "Adam Schenk", "John Senden", "Robby Shelton", "Webb Simpson", "Cameron Smith", "Jordan Spieth", "Brendan Steele", "Sepp Straka",
"Kevin Streelman", "Steve Stricker", "Brian Stuard", "Vaughn Taylor", "Josh Teater", "Justin Thomas", "Brendon Todd",
"Kevin Tway", "Peter Uihlein", "Erik van Rooyen", "Harold Varner III", "Jhonattan Vegas", "Jimmy Walker", "Matt Wallace", "Nick Watney", "Bubba Watson", "Richy Werenski", "Danny Willett", "Matthew Wolff",
"Gary Woodland", "Xinjun Zhang"];
