exports.field = ["24", "Byeong-Hun An", "Abraham Ancer", "Ryan Armour", "Aaron Baddeley", "Daniel Berger",
"Christiaan Bezuidenhout", "Scott Brown", "Wesley Bryan", "Bronson Burgoon", "Sam Burns", "Rafa Cabrera Bello",
"Bud Cauley", "Kevin Chappell", "K.J. Choi", "Stewart Cink", "Wyndham Clark", "Corey Conners", "Austin Cook",
"Joel Dahmen", "Glen Day", "Jason Day", "Bryson DeChambeau", "Luke Donald", "Jason Dufner", "Tyler Duncan",
"Ernie Els", "Harris English", "Matt Every", "Tony Finau", "Matthew Fitzpatrick", "Rickie Fowler",
"Dylan Frittelli", "Jim Furyk", "Sergio Garcia", "Brice Garnett", "Brian Gay", "Michael Gligic", "Lucas Glover",
"Talor Gooch", "Branden Grace", "Lanto Griffin", "Emiliano Grillo", "Bill Haas", "Chesson Hadley", "Adam Hadwin",
"Brian Harman", "Tyrrell Hatton", "David Hearn", "Russell Henley", "Jim Herman", "Harry Higgs", "Charley Hoffman",
"Tom Hoge", "Max Homa", "Billy Horschel", "Viktor Hovland", "Charles Howell III", "Mark Hubbard", "Mackenzie Hughes",
"Sungjae Im", "Jazz Janewattananond", "Dustin Johnson", "Zach Johnson", "Matt Jones", "Sung Kang", "Michael Kim",
"Si Woo Kim", "Kevin Kisner", "Patton Kizzire", "Russell Knox", "Brooks Koepka", "Jason Kokrak", "Matt Kuchar",
"Andrew Landry", "Bernhard Langer", "Nate Lashley", "Danny Lee", "Kyoung-hoon Lee", "Luke List", "Adam Long",
"Davis Love III", "Shane Lowry", "Peter Malnati", "Hideki Matsuyama", "Denny McCarthy", "Graeme McDowell", "Rory McIlroy",
"Maverick McNealy", "Troy Merritt", "Keith Mitchell", "Ryan Moore", "Collin Morikawa", "Sebastián Muñoz", "Kevin Na",
"Matthew NeSmith", "Joaquin Niemann", "Alex Noren", "Andy Ogletree", "Louis Oosthuizen", "Carlos Ortiz", "Ryan Palmer",
"C.T. Pan", "Pat Perez", "Victor Perez", "Scott Piercy", "J.T. Poston", "Ted Potter Jr", "Ian Poulter", "Andrew Putnam",
"Jon Rahm", "Spencer Ralston", "Chez Reavie", "Doc Redman", "Patrick Reed", "Patrick Rodgers", "Justin Rose", "Sam Ryder",
"Rory Sabbatini", "Xander Schauffele", "Scottie Scheffler", "Adam Schenk", "Charl Schwartzel", "Webb Simpson", "Vijay Singh",
"Roger Sloan", "Cameron Smith", "Brandt Snedeker", "JJ Spaun", "Jordan Spieth", "Scott Stallings", "Kyle Stanley", "Sepp Straka",
"Kevin Streelman", "Chris Stroud", "Brian Stuard", "Vaughn Taylor", "Justin Thomas", "Michael Thompson", "Brendon Todd",
"Martin Trainer", "Cameron Tringale", "Kevin Tway", "Bo Van Pelt", "Erik van Rooyen", "Harold Varner III", "Jhonattan Vegas",
"Jimmy Walker", "Matt Wallace", "Nick Watney", "Bubba Watson", "Danny Willett", "Aaron Wise", "Matthew Wolff", "Gary Woodland"];
