exports.field = ["48", "Mark Anderson", "Ryan Armour", "Arjun Atwal", "Aaron Baddeley", "Chris Baker", "Ricky Barnes", "Christiaan Bezuidenhout", "Lucas Bjerregaard",
"Zac Blair", "Ryan Blaum", "Dominic Bozzelli", "Keegan Bradley", "Joseph Bramlett", "Ryan Brehm", "Scott Brown", "Wesley Bryan", "Bronson Burgoon", "Sam Burns",
"Jonathan Byrd", "Rafa Cabrera Bello", "Sebastian Cappelen", "Roberto Castro", "Greg Chalmers", "Kevin Chappell", "Stewart Cink", "Wyndham Clark", "Austin Cook", "Cameron Davis", "Jason Day",
"Bryson DeChambeau", "Luke Donald", "Jason Dufner", "Tyler Duncan", "Harris English", "Matt Every", "Tony Finau", "Rickie Fowler", "Brian Gay", "Michael Gellerman", "Doug Ghim", "Rhein Gibson",
"Michael Gligic", "Lucas Glover", "Talor Gooch", "Will Gordon", "Branden Grace", "Lanto Griffin", "Emiliano Grillo", "Fabián Gómez", "Bill Haas", "Chesson Hadley", "Adam Hadwin", "Brandon Hagy",
"James Hahn", "Brian Harman", "Scott Harrington", "Tyrrell Hatton", "David Hearn", "Kramer Hickok", "Harry Higgs", "Bo Hoag", "Tom Hoge", "Beau Hossler", "Viktor Hovland", "Mark Hubbard",
"Sungjae Im", "Matt Jones", "Michael Kim", "Si Woo Kim", "Chris Kirk", "Kevin Kisner", "Patton Kizzire", "Russell Knox", "Peter Kuest", "Nate Lashley",
"Hank Lebioda", "Nelson Ledesma", "Kyoung-hoon Lee", "Tom Lewis", "Luke List", "Jamie Lovemark", "Peter Malnati", "Ben Martin", "Hideki Matsuyama", "Tyler McCumber", "Maverick McNealy", "Troy Merritt",
"Grayson Murray", "Sebastián Muñoz", "Kevin Na", "James Nicholas", "Seung-yul Noh", "Alex Noren", "Henrik Norlander", "Rob Oppenheim",
"CT Pan", "Cameron Percy", "Pat Perez", "JT Poston", "Ted Potter Jr", "Seamus Power", "Andrew Putnam", "Doc Redman", "Patrick Reed", "Wes Roach", "Patrick Rodgers",
"Sam Ryder", "Rory Sabbatini", "Scottie Scheffler", "Adam Schenk", "Charl Schwartzel", "Chase Seiffert", "John Senden", "Robby Shelton", "Webb Simpson", "Vijay Singh", "Roger Sloan", "Cameron Smith",
"Brandt Snedeker", "JJ Spaun", "Scott Stallings", "Kyle Stanley", "Shawn Stefani", "Sepp Straka", "Robert Streb", "Steve Stricker", "Chris Stroud",
"Brian Stuard", "Zack Sucher", "Hudson Swafford", "Ben Taylor", "Josh Teater", "Sahith Theegala", "Michael Thompson", "Brendon Todd", "DJ Trahan", "Martin Trainer", "Cameron Tringale",
"Kevin Tway", "Peter Uihlein", "Bo Van Pelt", "Erik van Rooyen", "Harold Varner III", "Kristoffer Ventura", "Johnson Wagner", "Jimmy Walker", "Matt Wallace", "Bubba Watson", "Richy Werenski", "Vincent Whaley",
"Tim Wilkinson", "Danny Willett", "Aaron Wise", "Matthew Wolff", "Xinjun Zhang"];
